// src/app/guides/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { GUIDES } from "@/content/docs";

export const runtime = "nodejs";

export const metadata: Metadata = {
  title: "FTP/SFTP Troubleshooting Guides",
  description:
    "Step-by-step guides to diagnose FTP, FTPS, and SFTP failures (DNS, TCP, auth, and directory listing).",
  alternates: { canonical: "https://ftpmonitor.com/guides" },
  openGraph: {
    title: "FTP/SFTP Troubleshooting Guides",
    description:
      "Step-by-step guides to diagnose FTP, FTPS, and SFTP failures (DNS, TCP, auth, and directory listing).",
    url: "https://ftpmonitor.com/guides",
    type: "website",
  },
};

export default function GuidesIndexPage() {
  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "48px 16px",
        background: "#0b0b0c",
        color: "#f5f5f6",
        fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial",
      }}
    >
      <div style={{ maxWidth: 920, margin: "0 auto" }}>
        <div style={{ fontSize: 13, opacity: 0.7, marginBottom: 12 }}>
          <Link href="/" style={{ textDecoration: "none", color: "inherit" }}>
            FTPMonitor
          </Link>{" "}
          <span style={{ opacity: 0.5 }}> / </span>
          <span>Guides</span>
        </div>

        <h1 style={{ margin: "0 0 10px 0", letterSpacing: -0.4 }}>
          Troubleshooting Guides
        </h1>
        <p style={{ margin: 0, opacity: 0.8, lineHeight: 1.6 }}>
          These guides map directly to your health check steps (DNS → TCP → Auth
          → List) so users can fix issues fast.
        </p>

        <div style={{ marginTop: 22 }}>
          <ul style={{ margin: 0, paddingLeft: 18, lineHeight: 1.9 }}>
            {GUIDES.map((g) => (
              <li key={g.slug}>
                <Link
                  href={`/guides/${g.slug}`}
                  style={{ color: "inherit", textDecoration: "none" }}
                >
                  {g.title}
                </Link>
                <span style={{ opacity: 0.65 }}> — {g.description}</span>
              </li>
            ))}
          </ul>
        </div>

        <div
          style={{
            marginTop: 42,
            paddingTop: 18,
            borderTop: "1px solid rgba(255,255,255,0.12)",
            fontSize: 12,
            opacity: 0.55,
          }}
        >
          Generated by ftpmonitor.com
        </div>
      </div>
    </main>
  );
}
