type StepKey = "dns" | "tcp" | "auth" | "list";
type Protocol = "ftp" | "ftps" | "sftp";

export type Step = {
  key: StepKey;
  ok: boolean;
  ms?: number;
  message: string;
  details?: Record<string, any>;
};

export type Result = {
  ok: boolean;
  protocol: Protocol;
  host: string;
  port: number;
  testedPath?: string;
  totalMs: number;
  steps: Step[];
  tips: string[];
};

function padRight(s: string, n: number) {
  return (s + " ".repeat(n)).slice(0, n);
}
function ms(v?: number) {
  return typeof v === "number" ? `${v}ms` : "";
}
function okWord(ok: boolean) {
  return ok ? "OK" : "FAIL";
}
function emoji(ok: boolean) {
  return ok ? "✅" : "❌";
}

export function toPretty(r: Result, helpUrl?: string) {
  const lines: string[] = [];
  lines.push("FTPMonitor");
  lines.push(`Host: ${r.host}`);
  lines.push(
    `Protocol: ${r.protocol.toUpperCase()}  Port: ${r.port}${r.testedPath ? `  Path: ${r.testedPath}` : ""}`,
  );
  lines.push("");

  for (const s of r.steps) {
    lines.push(
      `${padRight(s.key.toUpperCase(), 5)} ${padRight(emoji(s.ok), 2)} ${padRight(ms(s.ms), 8)} ${s.message}`,
    );
  }

  if (r.tips?.length) {
    lines.push("");
    lines.push("Tips:");
    for (const t of r.tips) lines.push(`- ${t}`);
  }

  lines.push("");
  lines.push(`Total: ${r.totalMs}ms`);
  if (helpUrl) lines.push(`Troubleshooting: ${helpUrl}`);
  lines.push(
    "Diagnose your FTP/FTPS/SFTP endpoints instantly: https://ftpmonitor.com",
  );
  return lines.join("\n");
}

export function toSlack(r: Result, helpUrl?: string) {
  const lines: string[] = [];
  lines.push("FTPMonitor Check");
  lines.push(`Host: ${r.host}`);
  lines.push(
    `Protocol: ${r.protocol.toUpperCase()}  Port: ${r.port}${r.testedPath ? `  Path: ${r.testedPath}` : ""}`,
  );
  lines.push("");

  for (const s of r.steps) {
    lines.push(
      `${padRight(s.key.toUpperCase(), 5)} ${emoji(s.ok)} ${padRight(ms(s.ms), 8)} ${s.message}`,
    );
  }

  if (r.tips?.length) {
    lines.push("");
    lines.push("Tips:");
    for (const t of r.tips) lines.push(`• ${t}`);
  }

  if (helpUrl) {
    lines.push("");
    lines.push(`Troubleshooting: ${helpUrl}`);
  }
  lines.push(
    "Diagnose your FTP/FTPS/SFTP endpoints instantly: https://ftpmonitor.com",
  );
  return lines.join("\n");
}

export function toJira(r: Result, helpUrl?: string) {
  const rows = r.steps
    .map(
      (s) =>
        `${padRight(s.key.toUpperCase(), 5)} ${padRight(okWord(s.ok), 4)} ${padRight(ms(s.ms), 8)} ${s.message}`,
    )
    .join("\n");

  const header =
    `h3. FTPMonitor Check\n` +
    `*Host:* ${r.host}\n` +
    `*Protocol:* ${r.protocol.toUpperCase()}  *Port:* ${r.port}${r.testedPath ? `  *Path:* ${r.testedPath}` : ""}\n\n` +
    `{code}\n${rows}\n{code}\n`;

  const tail = helpUrl ? `\n*Troubleshooting:* ${helpUrl}\n` : "\n";
  return header + tail;
}

export function toMarkdown(r: Result, helpUrl?: string) {
  const rows = r.steps
    .map(
      (s) =>
        `${padRight(s.key.toUpperCase(), 5)} ${padRight(okWord(s.ok), 4)} ${padRight(ms(s.ms), 8)} ${s.message}`,
    )
    .join("\n");

  return (
    `## FTPMonitor Check\n` +
    `- Host: ${r.host}\n` +
    `- Protocol: ${r.protocol.toUpperCase()}\n` +
    `- Port: ${r.port}\n` +
    (r.testedPath ? `- Path: ${r.testedPath}\n` : "") +
    `\n\`\`\`text\n${rows}\n\`\`\`\n\n` +
    (r.tips?.length
      ? `**Tips**\n${r.tips.map((t) => `- ${t}`).join("\n")}\n\n`
      : "") +
    (helpUrl ? `Troubleshooting: ${helpUrl}\n` : "") +
    `Generated by ftpmonitor.com\n`
  );
}
