// src/app/(docs)/_components/DocLayout.tsx
import Link from "next/link";
import type { Doc } from "@/content/docs";
import RelatedLinks from "./RelatedLinks";

export default function DocLayout({
  doc,
  related,
  children,
}: {
  doc: Doc;
  related: Doc[];
  children: React.ReactNode;
}) {
  const base = doc.type === "guide" ? "/guides" : "/errors";

  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "48px 16px",
        background: "#0b0b0c",
        color: "#f5f5f6",
        fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial",
      }}
    >
      <div style={{ maxWidth: 920, margin: "0 auto" }}>
        <div style={{ fontSize: 13, opacity: 0.7, marginBottom: 12 }}>
          <Link href="/" style={{ textDecoration: "none", color: "inherit" }}>
            FTPMonitor
          </Link>{" "}
          <span style={{ opacity: 0.5 }}> / </span>
          <Link
            href={base}
            style={{ textDecoration: "none", color: "inherit" }}
          >
            {doc.type === "guide" ? "Guides" : "Errors"}
          </Link>
          <span style={{ opacity: 0.5 }}> / </span>
          <span>{doc.title}</span>
        </div>

        <h1 style={{ margin: "0 0 10px 0", letterSpacing: -0.4 }}>
          {doc.title}
        </h1>
        <p style={{ margin: 0, opacity: 0.8, lineHeight: 1.6 }}>
          {doc.description}
        </p>

        <div style={{ marginTop: 18 }}>{children}</div>

        <div
          style={{
            marginTop: 42,
            paddingTop: 18,
            borderTop: "1px solid rgba(255,255,255,0.12)",
          }}
        >
          <RelatedLinks related={related} />
          <div style={{ marginTop: 16, fontSize: 12, opacity: 0.55 }}>
            Generated by ftpmonitor.com
          </div>
        </div>
      </div>
    </main>
  );
}
