// src/app/errors/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { ERRORS } from "@/content/docs";

export const runtime = "nodejs";

export const metadata: Metadata = {
  title: "FTP/SFTP Error Codes",
  description:
    "Common FTP/FTPS/SFTP error messages and how to resolve them quickly.",
  alternates: { canonical: "https://ftpmonitor.com/errors" },
  openGraph: {
    title: "FTP/SFTP Error Codes",
    description:
      "Common FTP/FTPS/SFTP error messages and how to resolve them quickly.",
    url: "https://ftpmonitor.com/errors",
    type: "website",
  },
};

export default function ErrorsIndexPage() {
  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "48px 16px",
        background: "#0b0b0c",
        color: "#f5f5f6",
        fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, Arial",
      }}
    >
      <div style={{ maxWidth: 920, margin: "0 auto" }}>
        <div style={{ fontSize: 13, opacity: 0.7, marginBottom: 12 }}>
          <Link href="/" style={{ textDecoration: "none", color: "inherit" }}>
            FTPMonitor
          </Link>{" "}
          <span style={{ opacity: 0.5 }}> / </span>
          <span>Errors</span>
        </div>

        <h1 style={{ margin: "0 0 10px 0", letterSpacing: -0.4 }}>
          Error Pages
        </h1>
        <p style={{ margin: 0, opacity: 0.8, lineHeight: 1.6 }}>
          Error codes and common messages mapped to fixes and related guides.
        </p>

        <div style={{ marginTop: 22 }}>
          <ul style={{ margin: 0, paddingLeft: 18, lineHeight: 1.9 }}>
            {ERRORS.map((e) => (
              <li key={e.slug}>
                <Link
                  href={`/errors/${e.slug}`}
                  style={{ color: "inherit", textDecoration: "none" }}
                >
                  {e.title}
                </Link>
                <span style={{ opacity: 0.65 }}> — {e.description}</span>
              </li>
            ))}
          </ul>
        </div>

        <div
          style={{
            marginTop: 42,
            paddingTop: 18,
            borderTop: "1px solid rgba(255,255,255,0.12)",
            fontSize: 12,
            opacity: 0.55,
          }}
        >
          Generated by ftpmonitor.com
        </div>
      </div>
    </main>
  );
}
